### ISSUE TITLE
[Android 14]compile engine error

### ISSUE THREAD

**Issue by lycstar** [mumumusuc/termux-flutter#27]
```bash
~/termux-flutter/engine $ make sync
/data/data/com.termux/files/usr/bin/python3 /data/data/com.termux/files/home/termux-flutter/engine/gclient.py sync  -DR --with_branch_heads --with_tags --no-history
Syncing projects: 100% (132/132), done.
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/termux-flutter/engine/subprocess2.py", line 147, in __init__
    super(Popen, self).__init__(args, **kwargs)
  File "/data/data/com.termux/files/usr/lib/python3.11/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/data/data/com.termux/files/usr/lib/python3.11/subprocess.py", line 1951, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'cipd'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/data/com.termux/files/home/termux-flutter/engine/metrics.py", line 297, in print_notice_and_exit
    yield
  File "/data/data/com.termux/files/home/termux-flutter/engine/gclient.py", line 4091, in <module>
    sys.exit(main(sys.argv[1:]))
             ^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/home/termux-flutter/engine/gclient.py", line 4077, in main
    return dispatcher.execute(OptionParser(), argv)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/home/termux-flutter/engine/subcommand.py", line 253, in execute
    return command(parser, args[1:])
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/home/termux-flutter/engine/gclient.py", line 3468, in CMDsync
    ret = client.RunOnDeps('update', args)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/home/termux-flutter/engine/gclient.py", line 2294, in RunOnDeps
    self._cipd_root.run(command)
  File "/data/data/com.termux/files/home/termux-flutter/engine/gclient_scm.py", line 1844, in run
    self.ensure()
  File "/data/data/com.termux/files/home/termux-flutter/engine/gclient_scm.py", line 1792, in ensure
    gclient_utils.CheckCallAndFilter(cmd,
  File "/data/data/com.termux/files/home/termux-flutter/engine/gclient_utils.py", line 638, in CheckCallAndFilter
    kid = subprocess2.Popen(args,
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/home/termux-flutter/engine/subprocess2.py", line 158, in __init__
    raise OSError(
OSError: Execution failed with error: [Errno 2] No such file or directory: 'cipd'.
Check that None or cipd exist and have execution permission.
make: *** [Makefile:80: sync] Error 1
```

**Comment by mumumusuc** [comment]
把engine目录加入PATH
```
cd engine
export PATH=$PATH:$(pwd)
```
如果还是相同的错误可能是Android14不支持
https://github.com/mumumusuc/termux-flutter/issues/26#issuecomment-2063703103

**Comment by lycstar** [comment]
@mumumusuc 一样的，不折腾了
